### DISCUSSION TITLE
BIRD raises Unexpected connect from unknown address error in bgp mode

### DISCUSSION THREAD

**Discussion by IterableTrucks** [openelb/openelb#362] [General]
I follow the `Use OpenELB in BGP Mode` page step by step but in step 7 the bird machine does not establish any route to bgp-svc service. And the journal of bird service tells  `Unexpected connect from unknown address 192.168.0.6 (port 39049)`. 
There are 5 nodes in k8s: 192.168.0.2(master)  192.168.0.3(worker) 192.168.0.4(worker) 192.168.0.5(worker) 192.168.0.6(worker). And the openelb-manager pod is running on 192.168.0.6. 
The bird service is running on the worker node at 192.168.0.3.
bgp-conf.yaml: 
```yaml
apiVersion: network.kubesphere.io/v1alpha2
kind: BgpConf
metadata:
  name: default
spec:
  as: 50000
  listenPort: 17900
  routerId: 192.168.0.2
```
bgp-peer.yaml:
```yaml
apiVersion: network.kubesphere.io/v1alpha2
kind: BgpPeer
metadata:
  name: bgp-peer
spec:
  conf:
    peerAs: 50001
    neighborAddress: 192.168.0.3
```
bird configuration:
```
router id 192.168.0.3;

protocol kernel {
        scan time 60;
        import none;
        export all;   # Actually insert routes into the kernel routing table
        merge paths on;
}

protocol device {
        scan time 60;
}
protocol bgp neighbor1 {
        local as 50001;
        neighbor 192.168.0.2 port 17900 as 50000;
        source address 192.168.0.3;
        import all;
        export all;
        enable route refresh off;
        add paths on;
}
```
k8s version is 1.26.5
openelb version is v0.5.1
