### ISSUE TITLE
[Feature] Provide the OpenELB Web UI for managing EIP and IP pool

### ISSUE THREAD

**Issue by renyunkang** [openelb/openelb#244]
### What we need
In the case of using openelb as the kubernetes load balancing implementation, the allocation of openelb external-ip-pool can only be viewed on the terminal interface by accessing kubernetes resources with kubectl. However, more and more kubernetes users are using specific dashboards to operate and manage clusters or workloads, such as kubesphere. Therefore, the current usage is not very friendly and convenient for users. OpenELB is still booming, we need a UI interface to simplify operation and adapt to the complexity later.
### Benefits of having it
You can clearly view the forwarding status of pod-service and the allocation of external-ip-pool. Simplify the management of ip-pool resources. At the same time, the UI interface can be more friendly to prompt the user to configure, making the operation easier.

**Comment by codering** [comment]
+1

**Comment by AnuragThePathak** [comment]
Hi, isn't this issue under LFX Mentorship Summer 2022?
The LFX website shows as no mentors found against this project.

**Comment by renyunkang** [comment]
You can find mentors in [cncf mentoring](https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2022/02-Summer#openelb). If you are interested in this, you can assign the issue to yourself.

**Comment by renyunkang** [comment]
For more details refer to the following link:

- https://openelb.github.io/docs/getting-started/configuration/configure-ip-address-pools-using-eip/
- https://openelb.github.io/docs/getting-started/configuration/configure-openelb-in-bgp-mode/

## EIP 

### Example 
```yaml
apiVersion: network.kubesphere.io/v1alpha2
kind: Eip
metadata:
    name: eip-sample-pool
    annotation:
      eip.openelb.kubesphere.io/is-default-eip: 'true'
spec:
    address: 192.168.0.91-192.168.0.100
    protocol: layer2
    interface: eth0
    disable: false
status:
    occupied: false
    usage: 1
    poolSize: 10
    used: 
      "192.168.0.91": "default/test-svc"
    firstIP: 192.168.0.91
    lastIP: 192.168.0.100
    ready: true
    v4: true
```

### Create

| Field | Description | Value |
| --- | --- | --- |
| metadata.name | Name of the Eip object | eip-sample-pool |
| metadata.annotation.eip.openelb.kubesphere.io/is-default-eip | set as default eip | true/false |
| spec.address | One or more IP addresses | `192.168.0.100` or `192.168.0.0/24` or `192.168.0.91-192.168.0.100` |
| spec.protocol | Specifies which mode of  Eip object is used for | layer2/vip/bgp |
| spec.interface | NIC name. This field is valid only when `protocol` is set to `layer2`. If the NIC names of the Kubernetes cluster nodes are different, you can set the value to `can_reach:IP address` | `can_reach:192.168.0.2` or `eth0` |
| spec.disable | Specifies whether the Eip object is disabled | true/false |

### Update

Only allow updates `spec.disable`

### Details / Status

| Field | Description | Value |
| --- | --- | --- |
| status.occupied | Specifies whether IP addresses have been used up | true/false |
| status.usage | Specifies how many IP addresses have been assigned | 1 |
| status.poolSize | Total number of IP addresses | 10 |
| status.used | Specifies the used IP addresses and the Services that use the IP addresses. | "192.168.0.91": "default/test-svc" |
| status.firstIP | First IP address | 192.168.0.91 |
| status.lastIP | Last IP address | 192.168.0.100 |
| status.ready | Specifies whether the Eip-associated program has been initialized. | true/false |
| status.v4 | Specifies whether the address family is IPv4 | true - ipv4 |

## BgpConf

### Example 

```yaml
apiVersion: network.kubesphere.io/v1alpha2
kind: BgpConf
metadata:
  name: default
spec:
  as: 50000
  listenPort: 17900
  routerId: 192.168.0.2
status:
  nodesConfStatus:
    node1:
      as: 50000
      routerId: 192.168.0.2
```

### Create / Update

| Field | Description |
| --- | --- |
| metadata.name | BgpConf object name, The default is `default`, which cannot be modified |
| spec.as | Local ASN |
| spec.listenPort | Port on which OpenELB listens |
| spec.routerId | Local router ID - IP address of the node |

### Details / Status

| Field | Description |
| --- | --- |
| status.nodesConfStatus | BgpConf object status |
| status.nodesConfStatus.node1.as | Local ASN |
| status.nodesConfStatus.node1.routerId | Local router ID - IP address of the node |

## BgpPeer

### Example 
```yaml
apiVersion: network.kubesphere.io/v1alpha2
kind: BgpPeer
metadata:
  name: bgppeer-sample
spec:
  conf:
    peerAs: 50001
    neighborAddress: 192.168.0.5
  afiSafis:
    - config:
        family:
          afi: AFI_IP
          safi: SAFI_UNICAST
        enabled: true
      addPaths:
        config:
          sendMax: 10
  nodeSelector:
    matchLabels:
      openelb.kubesphere.io/rack: leaf1
status:
  nodesPeerStatus:
    node1:
      peerState:
        messages:
          received:
            keepalive: "30"
            open: "1"
            total: "32"
            update: "1"
          sent:
            keepalive: "26"
            open: "1"
            total: "36"
            update: "9"
        neighborAddress: 192.168.0.5
        peerAs: 50001
        peerType: 1
        queues: {}
        routerId: 192.168.0.5
        sessionState: ESTABLISHED
      timersState:
        downtime: "2022-05-31T10:23:26Z"
        keepaliveInterval: "30"
        negotiatedHoldTime: "90"
        uptime: "2022-05-31T10:23:26Z"
```

### Create / Update

| Field | Description |
| --- | --- |
| metadata.name | Name of the BgpPeer object |
| spec.conf.peerAs | ASN of the peer BGP router |
| spec.conf.neighborAddress | IP address of the peer BGP router |
| spec.afiSafis.config.family | Specify the address family |
| spec.afiSafis.addPaths.config.sendMax | Maximum number of equivalent routes that OpenELB can send to the peer BGP router for Equal-Cost Multi-Path (ECMP) routing. The default value is `10`. |
| spec.nodeSelector.matchLabels.openelb.kubesphere.io/rack | Specify the peer BGP router that establishes the BGP connection |

### Details / Status

| Field | Description |
| --- | --- |
| status.nodesPeerStatus.peerState | BgpPeer neighbor information |
| status.nodesPeerStatus.timersState | record information about time |
