### ISSUE TITLE
IP cannot be recycled

### ISSUE THREAD

**Issue by renyunkang** [openelb/openelb#271]
When using openelb exposed loadbalancer type service and eip to delete concurrently, ip cannot be recycled.
/kind bug

**Comment by renyunkang** [comment]
**the result returns ok in vip mode when `kubectl apply -f vip.yaml`**
```yaml
apiVersion: network.kubesphere.io/v1alpha2
kind: Eip
metadata:
  name: vip-eip
spec:
  address: 172.16.0.230-172.16.0.250
  protocol: vip
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vip-openelb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vip-openelb
  template:
    metadata:
      labels:
        app: vip-openelb
    spec:
      containers:
        - image: luksa/kubia
          name: kubia
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: vip-svc
  annotations:
    lb.kubesphere.io/v1alpha1: openelb
    protocol.openelb.kubesphere.io/v1alpha1: vip
    eip.openelb.kubesphere.io/v1alpha2: vip-eip
spec:
  selector:
    app: vip-openelb
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
  externalTrafficPolicy: Cluster
```
```
root@master1:~/openelb# kubectl get cm -n openelb-system
NAME                    DATA   AGE
kube-root-ca.crt        1      7h19m
openelb-vip-configmap   1      7h18m
root@master1:~/openelb#
root@master1:~/openelb# kubectl  get svc
NAME         TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)        AGE
kubernetes   ClusterIP      10.233.0.1      <none>         443/TCP        4d19h
vip-svc      LoadBalancer   10.233.20.237   172.16.0.230   80:30847/TCP   7s
```
**the result returns ok when `kubectl delete -f vip.yaml`, but ConfigMap `openelb-vip-configmap` is not updated**
```
root@master1:~/openelb# kubectl get cm -n openelb-system
NAME                    DATA   AGE
kube-root-ca.crt        1      7h19m
openelb-vip-configmap   1      7h18m
root@master1:~/openelb#
root@master1:~/openelb# kubectl  get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.233.0.1   <none>        443/TCP   4d19h
```
