### ISSUE TITLE
Need to tolerate node-role.kubernetes.io/control-plane:NoSchedule taints

### ISSUE THREAD

**Issue by t106362512** [openelb/openelb#312]
**Describe the bug**

The Kubernetes project is moving away from offensive wording and as part of this KEP-2067 was accepted to replace the 
`node-role.kubernetes.io/master:NoSchedule` taint with 
`node-role.kubernetes.io/control-plane:NoSchedule`.

For the above reasons, additional tolerance needs to be added to allow it to be deployed to kubernetes v1.24 and above

**To Reproduce**

1. `kubectl apply -f https://raw.githubusercontent.com/openelb/openelb/v0.5.1/deploy/openelb.yaml`

**Expected behaviour**

- Refer to deployment in v0.5.1 [openelb.yaml](https://github.com/openelb/openelb/blob/v0.5.1/deploy/openelb.yaml) manifest.
  
  ```yaml
  apiVersion: apps/v1
  kind: Deployment
    name: openelb-manager
  spec:
    template:
      metadata:
        labels:
          app: openelb-manager
          control-plane: openelb-manager
      spec:
      ...
        tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
    ```

- So I figured it should be able to be deployed to the master node or the control panel node, but in kubernetes v1.24 it can only be deployed to worker nodes.

**Output**

- It can only be deployed on worker nodes

**Version Info**

- Version of Kubernetes: v1.24.4
- Version of OpenELB: v0.5.1

**Additional links**

- https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/README.md
- https://github.com/kubernetes/enhancements/issues/2067
- https://github.com/kubernetes/kubeadm/issues/2200
