### ISSUE TITLE
Which routerId to specify in bgpConfig when running multiple replicas?

### ISSUE THREAD

**Issue by tadejg** [openelb/openelb#315]
I'm trying to configure OpenELB in BGP mode with multiple replicas for HA. As part of the bgpConfig yaml I'm expected to provide a single routerId which is supposedly an IP address of one of the NICs available on the host machine. What should routerId be set to when OpenELB is running multiple replicas on different nodes?

I understand that routerId can be left blank and OpenELB will pick the first NIC's IP address, however that won't work in my case, since I want to use eth1's IP address instead of eth0's (eth0 has a public IP, but I want to run the cluster exclusively on the private network, which is connected to eth1).

```
apiVersion: network.kubesphere.io/v1alpha2
kind: BgpConf
metadata:
  name: default
spec:
  as: 50000
  listenPort: 17900
  routerId: 192.168.0.2 # What to put here when OpenELB is replicated across different nodes and you don't want to use the default NIC's IP?
```
