### ISSUE TITLE
What should EIP object address range be set to?

### ISSUE THREAD

**Issue by tadejg** [openelb/openelb#316]
After reading through the docs, I have a question regarding the EIP object when using BGP mode.

What IP range should you specify in the EIP config?
Does it need to be an unused range or can/should it be set to the k8s service IP range?

The way I initially understood OpenELB's BGP mode is that it uses BGP to advertise cluster service IPs to the leaf routers. This is why I can't see why OpenELB would need its own block of IPs and why it couldn't simply use the already configured service CIDR block assigned to services by k8s.

```
apiVersion: network.kubesphere.io/v1alpha2
kind: Eip
metadata:
    name: eip-sample-pool
    annotations:
      eip.openelb.kubesphere.io/is-default-eip: "true"
spec:
    address: 192.168.0.91-192.168.0.100 # What to put here? Can it be the same as service CIDR block?
    protocol: bgp
    disable: false
```
