### ISSUE TITLE
Eip object with can_reach leads to lo interface, not sure if this is a bug, some help would be appreciated

### ISSUE THREAD

**Issue by lwabish** [openelb/openelb#331]
**Describe the bug**
According to the log of openelb manager, my eip object leads to error: invalid interface lo

openelb manager pod is running on master1 with ip 172.16.236.152/24

Eip object is configuared as follow:
```yaml
status:
  firstIP: 172.16.236.40
  lastIP: 172.16.236.42
  poolSize: 3
  usage: 1
  used:
    172.16.236.40: ingress-nginx-controller/ingress-nginx-controller
  v4: true
spec:
  address: 172.16.236.40-172.16.236.42
  interface: can_reach:172.16.236.40
  protocol: layer2
```
After some basic code digging, I found the error originates from 
https://github.com/openelb/openelb/blob/806efb00e4ef047be9ae33b0472eb7aae2a153e0/pkg/speaker/layer2/responder.go#L33

I tried running ip route get with lb ip and other node ip, results:
```bash
root@master1:~# ip route get 172.16.236.40
local 172.16.236.40 dev lo src 172.16.236.40 uid 0
    cache <local>
root@master1:~# ip route get 172.16.236.154
172.16.236.154 dev enp175s0f0 src 172.16.236.152 uid 0
    cache
```
Why `ip route get` with lb ip got lo interface?Need some help to dig more deeply.

**To Reproduce**
At first openelb with the eip above is working correctly and 172.16.236.40 has already been allocated as shown above.But after a restart of openelb manager pod, this error occured. I am not sure if sriov network configuration interferes with openelb.

**Expected behaviour**

**Output**

**Version Info**

- Version of Kubernetes: 1.21.5
- Version of OpenELB: 0.4.4

**Comment by renyunkang** [comment]
> **Describe the bug** According to the log of openelb manager, my eip object leads to error: invalid interface lo
> 
> openelb manager pod is running on master1 with ip 172.16.236.152/24
> 
> Eip object is configuared as follow:
> 
> ```yaml
> status:
>   firstIP: 172.16.236.40
>   lastIP: 172.16.236.42
>   poolSize: 3
>   usage: 1
>   used:
>     172.16.236.40: ingress-nginx-controller/ingress-nginx-controller
>   v4: true
> spec:
>   address: 172.16.236.40-172.16.236.42
>   interface: can_reach:172.16.236.40
>   protocol: layer2
> ```
> 
> After some basic code digging, I found the error originates from
> 
> https://github.com/openelb/openelb/blob/806efb00e4ef047be9ae33b0472eb7aae2a153e0/pkg/speaker/layer2/responder.go#L33
> 
> I tried running ip route get with lb ip and other node ip, results:
> 
> ```shell
> root@master1:~# ip route get 172.16.236.40
> local 172.16.236.40 dev lo src 172.16.236.40 uid 0
>     cache <local>
> root@master1:~# ip route get 172.16.236.154
> 172.16.236.154 dev enp175s0f0 src 172.16.236.152 uid 0
>     cache
> ```
> 
> Why `ip route get` with lb ip got lo interface?Need some help to dig more deeply.
> 
> **To Reproduce** At first openelb with the eip above is working correctly and 172.16.236.40 has already been allocated as shown above.But after a restart of openelb manager pod, this error occured. I am not sure if sriov network configuration interferes with openelb.
> 
> **Expected behaviour**
> 
> **Output**
> 
> **Version Info**
> 
> * Version of Kubernetes: 1.21.5
> * Version of OpenELB: 0.4.4

Why are you using 172.16.236.40 instead of 172.16.236.152?
```yaml
... ...
spec:
  address: 172.16.236.40-172.16.236.42
  interface: can_reach:172.16.236.152
```
