### ISSUE TITLE
can't use custom keepavled image

### ISSUE THREAD

**Issue by danielye77** [openelb/openelb#337]
**Describe the bug**

i install k8s in local network,
I set a configmap openelb-vip-image,but openelp-keepalvied-vip ds image still kubesphere/kube-keepalvied-vip:0.35,it doesn't use image in CM

**To Reproduce**

**Expected behaviour**

**Output**

**Version Info**

- Version of Kubernetes: 1.27.3
- Version of OpenELB:  0.5.1

**Comment by renyunkang** [comment]
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: openelb-images
  namespace: openelb-system
data:
  keepalived-vip-image: kubesphere/kube-keepalived-vip:0.35
```
1. Please confirm whether the configuration of configmap is correct. 
2. The configmap should be in the same namespace as `openelb-manager`.
