### ISSUE TITLE
Changing and Managing Eip address pools

### ISSUE THREAD

**Issue by bdowling** [openelb/openelb#391]
Is there an easy/recommended process for changing VIP pool ranges.  I see that the only change currently allowed is spec.disable.

https://github.com/openelb/openelb/blob/683938d2c9195fd0b49079a9fc4a24d432482852/api/v1alpha2/eip_types.go#L209

It would be nice if you could adjust the range as needed without impacting existing LoadBalanced services.  It seem like if I delete and create the pool, the LoadBalanced services will move around since the status field is not accepted on creating the `Eip` object.  So any services that did not Pin their IP address will get new IP addresses.

Additionally, is there any way to "blacklist" IPs in the pool range if a need occurred?

**Comment by bdowling** [comment]
fwiw, it's a bit of a kludge, but I did find that I could statically assign IP to a service that has an invalid selector, e.g. no backing pods found, and openelb does not advertise the IP.

```
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 10.80.10.21
  ports:
  - name: empty
    nodePort: 31458
    port: 1
    protocol: UDP
    targetPort: 1
  selector:
    blacklisted: blacklisted-ips
  sessionAffinity: None
  type: LoadBalancer
  ```
