### ISSUE TITLE
Layer2 EIP validated incorrectly

### ISSUE THREAD

**Issue by richard-fairthorne** [openelb/openelb#456]
**Describe the bug**

Creation of EIP fails with ```eth0's ip and the eip[192.168.0.91-192.168.0.100] are not in the same network segment```. It should not be a requirement that the IP's are in the same segment as the interface.

**To Reproduce**

Given the following

```yaml
apiVersion: network.kubesphere.io/v1alpha2
kind: Eip
metadata:
  name: layer2-eip
spec:
  address: 192.168.0.91-192.168.0.100
  interface: eth0
  protocol: layer2
```

**Expected behaviour**

The EIP should be created, and arp should respond on eth0

**Output**

```eth0's ip and the eip[192.168.0.91-192.168.0.100] are not in the same network segment```

**Version Info**

- Version of Kubernetes:
- Version of OpenELB: 0.6.0
